### PR TITLE
Create Cape Command. 

### PR DESCRIPTION
**Pull request by vypr-ysl**
This command allows you to search in capes.json whether you have a cape in-game or not. You search using your UUID (dashed), and it will resolve your Username, show your Cape Image and Cape Type.

- New Package Required:
node-fetch (npm i node-fetch)

### CODE REVIEW

**Comment by humboldt123** [comment]
Thanks!

**Comment by vypr-ysl** [comment]
No problem! Please make sure to install node-fetch before restarting the bot.

**Comment by l1ving** [comment]
I don't understand why this was merged when bot-kt already has this

**Comment by l1ving** [comment]
Also the new cape format is incompatible with this, making it pretty useless

**Comment by humboldt123** [comment]
For the music fixes.

**Comment by l1ving** [comment]
those were already merged, you're just being memed by non linear git history

**Comment by vypr-ysl** [comment]
> Also the new cape format is incompatible with this, making it pretty useless

I see you already have the cape attach command, and cape list command in bot-kt, I suppose an individual cape search command wouldn't hurt?

**Comment by vypr-ysl** [comment]
I am happy to adapt it to your new cape format in the future.

**Comment by l1ving** [comment]
> I suppose an individual cape search command wouldn't hurt?

> Also the new cape format is incompatible with this, making it pretty useless

**Comment by vypr-ysl** [comment]
> I am happy to adapt it to your new cape format in the future.

**Comment by l1ving** [comment]
slow internet moment

**Comment by l1ving** [comment]
I'd rather it be an optional argument in cape list

**Comment by vypr-ysl** [comment]
Sure, you can add into the cape list argument.

**Comment by vypr-ysl** [comment]
@l1ving Should I adapt the command to the new cape system?

**Comment by l1ving** [comment]
Yes, but I'd prefer it to be a sub argument in cape list for bot-kt

**Comment by vypr-ysl** [comment]
Sounds good, I will devise something new once your new cape system is rolled out!

**Comment by l1ving** [comment]
Thanks. The command is finished, it's only waiting for changes in the client repo

**Pull request merged**
