### PR TITLE
fix ur random cat gen

### PR DESCRIPTION
**Pull request by CesiumCs**
i forgot to put semis after like half of this but i cba to fix it
this is probably the shittiest implementation possible but i am so new to this

### CODE REVIEW

**Review by l1ving — APPROVED** [review]
approved

**Comment by sourTaste000** [comment]
discord is caching the image so random doesn't work

**Comment by CesiumCs** [comment]
?
image
it wasnt working before because someone was treating a string like an array

**Comment by CesiumCs** [comment]
i understand now. discord cached rotator.php so someone added code that was *supposed* to tack on some extra letters to make discord get it fresh. but that didnt work because treating a string like an array made it just request rotator.php?undefined instead of ?asdfbnwhatever.

**Pull request merged**
