### PR TITLE
Unhandled Rejection Logging

### PR DESCRIPTION
**Pull request by ezBot03**
Now living won't have to go in VPS and check logs :P, we will get instant reports in the logchannel and create a PR to fix whatever happened.

### CODE REVIEW

**Comment by ezBot03** [comment]
No conflicts this time lol

**Comment by ezBot03** [comment]
Only updated main.js

**Comment by ezBot03** [comment]
why is non-linear git history to stupid

**Comment by ezBot03** [comment]
I only want to add 1 thing, and it says "merge 11 commits" lol

**Comment by l1ving** [comment]
bruh update your branch then

**Pull request closed without merging**
