### PR TITLE
Create Loop Command.

### PR DESCRIPTION
**Pull request by vypr-ysl**
- Created Loop Command, refer to sound.loop.js.
- Updated Lofi for the new ytdl library.
- Added a check in all music commands so only people in the same Voice Channel as the client can use the command.
- Updated play command's suitability for the loop command to function properly.

### CODE REVIEW

**Comment by humboldt123** [comment]
Please resolve conflics

**Comment by vypr-ysl** [comment]
Could you please specify where?

**Comment by vypr-ysl** [comment]
Nevermind, I know where it is.

**Comment by vypr-ysl** [comment]
Conflicts have been resolved.

**Review by l1ving — APPROVED** [review]

**Comment by vypr-ysl** [comment]
Thank you!

**Pull request merged**
