### PR TITLE
Add my Discord ID to update command.

### PR DESCRIPTION
**Pull request by ezBot03**
688398900721352716 is my ID (ez#6969), I think it would be efficient to have this as I am a verified bot dev on Discord, and I'll probably be making often PR's and since others time-zones are different, I'd make a great maintainer.

### CODE REVIEW

**Comment by ezBot03** [comment]
yes, i need gib thanks, i fix moosik stuff :3

**Comment by sourTaste000** [comment]
:trollface:

**Comment by ezBot03** [comment]
DO IT

**Comment by humboldt123** [comment]
No. This will not be merged for security reasons.

**Comment by ezBot03** [comment]
Bruh man really said security reasons

**Comment by ezBot03** [comment]
do it or no music pull request :trollface:

**Comment by ezBot03** [comment]
cringe cringe cringe <@297096161842429963> <@297096161842429963> gimme

**Comment by sourTaste000** [comment]
do it no balls

**Comment by humboldt123** [comment]
Can we try to be more professional?

**Pull request closed without merging**
